# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """$os$username$hostname$kubernetes$directory$git_branch$git_status$nodejs$golang$python $character"""

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](blue)"

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Ubuntu  = "󰕈"
Arch    = "󰣇"
Macos   = ""

# ---y

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
truncation_length = 4
truncate_to_repo  = true
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = "[⚡$count ](bold red)"
up_to_date = '[󰘽 up-to-date](green) '
untracked  = "[?$count ](bold white)"
ahead      = "[⇡$count ](bold cyan)"
behind     = "[⇣$count ](bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold cyan)"
stashed = '[ stashed=${count}](green) '
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
renamed = '[󱍸 renamed=${count}](yellow) '
deleted    = "[✘$count ](bold red)"

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[ruby]
disabled = true

